package gui;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import wahtsup.GUIHandler;
import wahtsup.WhatsUp;
import wahtsup.WriterClass;

public class Chat extends JPanel {
    public JLabel jcomp1;
    public JLabel jcomp2;
    public JTextField jcomp3;
    public JButton JButtonInvio;
    public JLabel JLabelStanza;
    public JLabel JLabelPartecipanti;
    public JButton JButtonEsci;

    public Chat() {
        //construct components
        jcomp1 = new JLabel("pROVA1");
        jcomp2 = new JLabel("prova2");
        jcomp3 = new JTextField (5);
        JButtonInvio = new JButton ("I");
        JLabelStanza = new JLabel ("");
        JLabelPartecipanti = new JLabel (Stanze.selectedRoom);
        JButtonEsci = new JButton ("Esci");

        //adjust size and set layout
        setPreferredSize (new Dimension (598, 393));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (JButtonInvio);
        add (JLabelStanza);
        add (JLabelPartecipanti);
        add (JButtonEsci);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (15, 45, 435, 310);
        jcomp2.setBounds (460, 45, 130, 310);
        jcomp3.setBounds (15, 360, 390, 25);
        JButtonInvio.setBounds (410, 360, 40, 25);
        JLabelStanza.setBounds (25, 15, 100, 25);
        JLabelPartecipanti.setBounds (95, 15, 100, 25);
        JButtonEsci.setBounds (515, 10, 65, 25);
        
        JButtonInvio.addActionListener((ActionEvent e) ->
        {
            WriterClass.instance.WriteComunication(jcomp3.getText());
        });
        
        JButtonEsci.addActionListener((ActionEvent e) ->
        {
            WriterClass.instance.RemoveMeFromRoom();
            GUIHandler.instance.LoadShowRoom();
        });
    }

    public void SetPartecipati(String[] partecipanti)
    {
        for (String partecipante : partecipanti)
        {
            System.out.println("Adding to Partecipanti: " + partecipante );
            jcomp2.setText(partecipante + "\n");
        }
    }
    
    public void AddNewMessageChat(String msg, String nickName, int color)
    {
        jcomp1.setText(jcomp1.getText() + "\n" + nickName + ": " + msg);
    }

    public void ResetChatAndPartecipanti()
    {
        jcomp1.setText("");
        jcomp2.setText("");
    }
    
    
        
//    public static void main (String[] args) {
//        JFrame frame = new JFrame ("Chat");
//        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
//        frame.getContentPane().add (new Chat());
//        frame.pack();
//        frame.setVisible (true);
//    }
}
