package gui;

//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Chat extends JPanel {
    private JTextArea jcomp1;
    private JTextArea jcomp2;
    private JTextField jcomp3;
    private JButton JButtonInvio;
    private JLabel JLabelStanza;
    private JLabel JLabelPartecipanti;
    private JButton JButtonEsci;

    public Chat() {
        //construct components
        jcomp1 = new JTextArea (5, 5);
        jcomp2 = new JTextArea (5, 5);
        jcomp3 = new JTextField (5);
        JButtonInvio = new JButton ("I");
        JLabelStanza = new JLabel ("Stanza");
        JLabelPartecipanti = new JLabel ("5");
        JButtonEsci = new JButton ("Esci");

        //adjust size and set layout
        setPreferredSize (new Dimension (598, 393));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (JButtonInvio);
        add (JLabelStanza);
        add (JLabelPartecipanti);
        add (JButtonEsci);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds (15, 45, 435, 310);
        jcomp2.setBounds (460, 45, 130, 310);
        jcomp3.setBounds (15, 360, 390, 25);
        JButtonInvio.setBounds (410, 360, 40, 25);
        JLabelStanza.setBounds (25, 15, 100, 25);
        JLabelPartecipanti.setBounds (95, 15, 100, 25);
        JButtonEsci.setBounds (515, 10, 65, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Chat");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Chat());
        frame.pack();
        frame.setVisible (true);
    }
}
