//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import wahtsup.GUIHandler;
import wahtsup.WriterClass;

public class Entrata extends JPanel
{

    public JLabel JLabelWelcome;
    public JLabel JLabelPass;
    public JPasswordField JTextFieldPass;
    public JLabel errorLabel;
    public JButton jcomp4;
    public JButton jcomp5;

    public Entrata()
    {
        //construct components
        JLabelWelcome = new JLabel("Welcome to " + Stanze.selectedRoom);
        JLabelPass = new JLabel("Password: ");
        errorLabel = new JLabel();
        JTextFieldPass = new JPasswordField(5);
        jcomp4 = new JButton("Esci");
        jcomp5 = new JButton("Continua");

        //adjust size and set layout
        setPreferredSize(new Dimension(309, 184));
        setLayout(null);

        //add components
        add(JLabelWelcome);
        add(JLabelPass);
        add(JTextFieldPass);
        add(jcomp4);
        add(jcomp5);
        add(errorLabel);
        //set component bounds (only needed by Absolute Positioning)
        JLabelWelcome.setBounds(40, 20, 200, 25);
        errorLabel.setBounds(40, 50, 200, 25);
        JLabelPass.setBounds(55, 80, 100, 25);
        JTextFieldPass.setBounds(135, 80, 100, 25);
        jcomp4.setBounds(110, 130, 60, 25);
        jcomp5.setBounds(175, 130, 85, 25);
        
        jcomp5.addActionListener((ActionEvent e) ->
        {
            WriterClass.instance.AddMeToRoom(Stanze.selectedRoomId, String.valueOf(JTextFieldPass.getPassword()));
        });
        jcomp4.addActionListener((ActionEvent e) ->
        {
            GUIHandler.instance.LoadShowRoom();
        });
    }

    public void ShowErrorLoginMsg(String msg)
    {
        errorLabel.setText("<html><font color = red >" + msg + "</font></html>");
    }
    
    public void ResetErrorLabel()         
    {
        
    }
//    public static void main (String[] args) {
//        JFrame frame = new JFrame ("Nuova");
//        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
//        frame.getContentPane().add (new Nuova());
//        frame.pack();
//        frame.setVisible (true);
//    }
}
