//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Entrata extends JPanel {
    private JLabel JLabelWelcome;
    private JLabel JLabelPass;
    private JPasswordField JTextFieldPass;
    private JButton jcomp4;
    private JButton jcomp5;

    public Entrata() {
        //construct components
        JLabelWelcome = new JLabel ("Welcome to ");
        JLabelPass = new JLabel ("Password: ");
        JTextFieldPass = new JPasswordField (5);
        jcomp4 = new JButton ("Esci");
        jcomp5 = new JButton ("Continua");

        //adjust size and set layout
        setPreferredSize (new Dimension (309, 184));
        setLayout (null);

        //add components
        add (JLabelWelcome);
        add (JLabelPass);
        add (JTextFieldPass);
        add (jcomp4);
        add (jcomp5);

        //set component bounds (only needed by Absolute Positioning)
        JLabelWelcome.setBounds (80, 20, 100, 25);
        JLabelPass.setBounds (55, 80, 100, 25);
        JTextFieldPass.setBounds (135, 80, 100, 25);
        jcomp4.setBounds (110, 130, 60, 25);
        jcomp5.setBounds (175, 130, 85, 25);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Nuova");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Nuova());
        frame.pack();
        frame.setVisible (true);
    }
}
