//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package gui;

import gui.ColorChooserButton.ColorChangedListener;
import java.awt.*;
import java.awt.event.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.event.*;
import wahtsup.GUIHandler;
import wahtsup.MessageHandler;
import wahtsup.WhatsUp;
import wahtsup.WriterClass;

public class Login extends JPanel
{

    public JLabel JLabelNickname;
    public JTextField JTextFieldNick;
    public JLabel JLabelColor;
    public JLabel JLabelIP;
    public JTextField JTextFieldIP;
    public JButton JButtonContinua;
    public JCheckBox JCheckBoxCondizioni;
    public JLabel errorLabel;

    public Login()
    {
        //construct components
        JLabelNickname = new JLabel("Nickname: ");
        JTextFieldNick = new JTextField(10);
        JLabelColor = new JLabel("Favorite color:");
        JLabelIP = new JLabel("IP Address: ");
        JTextFieldIP = new JTextField(5);
        JButtonContinua = new JButton("Continue");
        JCheckBoxCondizioni = new JCheckBox("Dichiaro di avere letto e accettato le condizioni di servizio");
        ColorChooserButton colorChooser = new ColorChooserButton(Color.BLACK);
        errorLabel = new JLabel();

        //adjust size and set layout
        setPreferredSize(new Dimension(371, 317));
        setLayout(null);

        //add components
        add(colorChooser);
        add(JLabelNickname);
        add(JTextFieldNick);
        add(JLabelColor);
        add(JLabelIP);
        add(JTextFieldIP);
        add(JButtonContinua);
        add(JCheckBoxCondizioni);
        add(errorLabel);
        //set component bounds (only needed by Absolute Positioning)
        colorChooser.addColorChangedListener((Color newColor) ->
        {
            // do something with newColor ...
        });
        colorChooser.setBounds(215, 80, 25, 25);
        JLabelNickname.setBounds(100, 40, 100, 25);
        JTextFieldNick.setBounds(185, 40, 100, 25);
        JLabelColor.setBounds(80, 80, 100, 25);
        JLabelIP.setBounds(90, 150, 100, 25);
        JTextFieldIP.setBounds(185, 150, 100, 25);
        JButtonContinua.setBounds(35, 240, 100, 25);
        JCheckBoxCondizioni.setBounds(10, 270, 375, 60);
        errorLabel.setBounds(30, 180, 340, 50);
        JButtonContinua.addActionListener((ActionEvent ae) ->
        {
            if (JLabelNickname.getText().isEmpty() || JLabelNickname.getText().contains(":"))
            {
                errorLabel.setText("<html><font color = red >pls Insert a valid Username</font></html>");

            }
            if (!JCheckBoxCondizioni.isSelected())
            {
                errorLabel.setText("<html><font color = red >U have to check the terms and conditions box</font></html>");
                return;
            }
            try
            {
                WhatsUp.SetSocketParameter(JTextFieldIP.getText());
                System.out.println(JTextFieldNick.getText());
                WriterClass.instance.PresentateMySelf(JTextFieldNick.getText(), colorChooser.getSelectedColor());
                GUIHandler.instance.LoadShowRoom();

            } catch (IOException ex)
            {
                errorLabel.setText("<html><font color = red >Error creating Connection to the server, check the parameters then retry later on</font></html>");
                System.out.println("Error creating socket: " + ex);
            }

        });
    }

//    public static void main(String[] args) {
//        JFrame frame = new JFrame("Login");
//        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        frame.getContentPane().add(new Login());
//        frame.pack();
//        frame.setVisible(true);
//    }
}
