//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

package gui;

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;
import wahtsup.GUIHandler;
import wahtsup.WhatsUp;
import wahtsup.WriterClass;

/**
 *
 * @author davide
 */
public class Nuova extends JPanel {
    public JLabel jcomp1;
    public JLabel jcomp2;
    public JLabel jcomp3;
    public JPasswordField JTextFieldPass1;
    public JPasswordField JTextFieldPass2;
    public JTextField JTextFieldNome;
    public JLabel jcomp7;
    public JButton JButtonEsci;
    public JButton JButtonCrea;
    public JSpinner max;
    
    public Nuova() {
        //construct components
        jcomp1 = new JLabel ("Nome stanza:");
        jcomp2 = new JLabel ("Password:");
        jcomp3 = new JLabel ("Conferma password:");
        JTextFieldPass1 = new JPasswordField (5);
        JTextFieldPass2 = new JPasswordField (5);
        JTextFieldNome = new JTextField (5);
        jcomp7 = new JLabel ("Numero MAX persone");
        JButtonEsci = new JButton ("Esci");
        JButtonCrea = new JButton ("Crea");
        max = new JSpinner(new SpinnerNumberModel(10,1,254,1));

        //adjust size and set layout
        setPreferredSize (new Dimension (301, 272));
        setLayout (null);

        //add components
        add (jcomp1);
        add (jcomp2);
        add (jcomp3);
        add (JTextFieldPass1);
        add (JTextFieldPass2);
        add (JTextFieldNome);
        add (jcomp7);
        add (JButtonEsci);
        add (JButtonCrea);
        add (max);

        //set component bounds (only needed by Absolute Positioning)
        //x;y;w;h
        jcomp1.setBounds (70, 25, 100, 25);
        jcomp2.setBounds (85, 55, 100, 25);
        jcomp3.setBounds (25, 85, 150, 25);
        
        JTextFieldPass1.setBounds (190, 55, 100, 25);
        JTextFieldPass2.setBounds (190, 85, 100, 25);
        JTextFieldNome.setBounds (190, 25, 100, 25);
        jcomp7.setBounds (10, 165, 160, 25);
        max.setBounds(190, 165, 100, 25);
        JButtonEsci.setBounds (115, 235, 70, 25);
        
        JButtonCrea.setBounds (190, 235, 100, 25);
        
        
        JButtonCrea.addActionListener((ActionEvent e) ->
        {
            WriterClass.instance.CreateARoom(JTextFieldNome.getText(), String.valueOf(JTextFieldPass1.getPassword()), (int)max.getValue());
        });
        
        JButtonEsci.addActionListener((ActionEvent e) ->
        {
            GUIHandler.instance.LoadShowRoom();
        });
    }


//    public static void main (String[] args) {
//        JFrame frame = new JFrame ("Nuova");
//        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
//        frame.getContentPane().add (new Nuova());
//        frame.pack();
//        frame.setVisible (true);
//    }
}
