//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!
package gui;

import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.ListDataListener;
import wahtsup.GUIHandler;
import wahtsup.WriterClass;
@SuppressWarnings("unchecked")
public class Stanze extends JPanel
{

    public JList jcomp1;
    public JButton JButtonNuova;
    public JButton JButtonAggiorna;
    public JButton JButtonEsci;
    public JButton JButtonPartecipa;
    public DefaultListModel<String> roomsList;
    public ArrayList<Integer> roomsListId;
    public static String selectedRoom = "";
    public static int selectedRoomId;

    public Stanze()
    {
        //construct components
        roomsList = new DefaultListModel<String>();
        roomsListId = new ArrayList<>();
        jcomp1 = new JList<String>(roomsList);
        //roomsList.addElement("Testoso");

        JButtonNuova = new JButton("Nuova stanza");
        JButtonAggiorna = new JButton("Aggiorna");
        JButtonEsci = new JButton("Esci");
        JButtonPartecipa = new JButton("Partecipa");

        //adjust size and set layout
        setPreferredSize(new Dimension(465, 392));
        setLayout(null);

        //add components
        add(jcomp1);
        add(JButtonNuova);
        add(JButtonAggiorna);
        add(JButtonEsci);
        add(JButtonPartecipa);

        //set component bounds (only needed by Absolute Positioning)
        jcomp1.setBounds(110, 20, 330, 300);
        JButtonNuova.setBounds(25, 335, 110, 25);
        JButtonAggiorna.setBounds(170, 335, 85, 25);
        JButtonEsci.setBounds(285, 335, 60, 25);
        JButtonPartecipa.setBounds(350, 335, 90, 25);

        JButtonNuova.addActionListener((ActionEvent e) ->
        {
            GUIHandler.instance.LoadNewRoomCreator();
        });

        JButtonAggiorna.addActionListener((ActionEvent e) ->
        {
            AskForCreatedRooms();
        });

        JButtonEsci.addActionListener((ActionEvent e) ->
        {
            GUIHandler.instance.CloseTheProgram();
        });

        JButtonPartecipa.addActionListener((ActionEvent e) ->
        {
            try
            {
                selectedRoom = (String) jcomp1.getSelectedValue();
                selectedRoomId = roomsListId.get(roomsList.indexOf(selectedRoom));
                GUIHandler.instance.LoadLoginRoom();
            } catch (Exception ex)
            {

            }
        });
        jcomp1.setCellRenderer(new DefaultListCellRenderer());

    }

//    public static void main (String[] args) {
//        JFrame frame = new JFrame ("Stanze");
//        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
//        frame.getContentPane().add (new Stanze());
//        frame.pack();
//        frame.setVisible (true);
//    }
    public void AskForCreatedRooms()
    {
        WriterClass.instance.AskForAvailableRooms();
    }

    public void AddNewRoomToList(String roomName, int idRoom)
    {
        roomsList.addElement(roomName);
        roomsListId.add(idRoom);
    }

    public void ResetListRoom()
    {
        roomsList.clear();
        roomsListId.clear();
    }
}
