//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class Login extends JPanel {
    private JButton JButtonColor;
    private JLabel JLabelNickname;
    private JTextField JTextFieldNick;
    private JLabel JLabelColor;
    private JLabel JLabelIP;
    private JTextField JTextFieldIP;
    private JLabel JLabelHost;
    private JTextField jcomp8;
    private JButton JButtonContinua;
    private JCheckBox JCheckBoxCondizioni;

    public Login() {
        //construct components
        JButtonColor = new JButton ("");
        JLabelNickname = new JLabel ("Nickname: ");
        JTextFieldNick = new JTextField (10);
        JLabelColor = new JLabel ("Favorite color:");
        JLabelIP = new JLabel ("IP Address: ");
        JTextFieldIP = new JTextField (5);
        JLabelHost = new JLabel ("Host:");
        jcomp8 = new JTextField (5);
        JButtonContinua = new JButton ("Continue");
        JCheckBoxCondizioni = new JCheckBox ("Dichiaro di avere letto e accettato le condizioni di servizio");

        //adjust size and set layout
        setPreferredSize (new Dimension (371, 317));
        setLayout (null);

        //add components
        add (JButtonColor);
        add (JLabelNickname);
        add (JTextFieldNick);
        add (JLabelColor);
        add (JLabelIP);
        add (JTextFieldIP);
        add (JLabelHost);
        add (jcomp8);
        add (JButtonContinua);
        add (JCheckBoxCondizioni);

        //set component bounds (only needed by Absolute Positioning)
        JButtonColor.setBounds (215, 80, 25, 25);
        JLabelNickname.setBounds (100, 40, 100, 25);
        JTextFieldNick.setBounds (185, 40, 100, 25);
        JLabelColor.setBounds (80, 80, 100, 25);
        JLabelIP.setBounds (90, 150, 100, 25);
        JTextFieldIP.setBounds (185, 150, 100, 25);
        JLabelHost.setBounds (125, 190, 45, 25);
        jcomp8.setBounds (185, 190, 100, 25);
        JButtonContinua.setBounds (35, 240, 100, 25);
        JCheckBoxCondizioni.setBounds (10, 245, 375, 60);
    }


    public static void main (String[] args) {
        JFrame frame = new JFrame ("Login");
        frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
        frame.getContentPane().add (new Login());
        frame.pack();
        frame.setVisible (true);
    }
}
